// <auto-generated />
using System;
using ExpenseTrackerApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTrackerApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701141606_SeedTestData")]
    partial class SeedTestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTrackerApi.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LimitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CategoryId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("Budgets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0001-000000000001"),
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimitAmount = 30000m,
                            Month = 7,
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0001-000000000002"),
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimitAmount = 12000m,
                            Month = 7,
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0001-000000000003"),
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimitAmount = 25000m,
                            Month = 7,
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0001-000000000004"),
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimitAmount = 10000m,
                            Month = 7,
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0001-000000000005"),
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimitAmount = 20000m,
                            Month = 7,
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0001-000000000006"),
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimitAmount = 30000m,
                            Month = 6,
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0001-000000000007"),
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimitAmount = 12000m,
                            Month = 6,
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0001-000000000008"),
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimitAmount = 25000m,
                            Month = 6,
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0002-000000000001"),
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimitAmount = 20000m,
                            Month = 7,
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0002-000000000002"),
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimitAmount = 30000m,
                            Month = 7,
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0002-000000000003"),
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimitAmount = 10000m,
                            Month = 7,
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            Year = 2026
                        });
                });

            modelBuilder.Entity("ExpenseTrackerApi.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            Color = "#4CAF50",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            Name = "Élelmiszer"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000002"),
                            Color = "#2196F3",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            Name = "Közlekedés"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000003"),
                            Color = "#9C27B0",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            Name = "Szórakozás"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000004"),
                            Color = "#F44336",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            Name = "Számlák"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000005"),
                            Color = "#FF9800",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            Name = "Egészség"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000006"),
                            Color = "#607D8B",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            Name = "Egyéb"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000007"),
                            Color = "#00BCD4",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = false,
                            Name = "Sport",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000008"),
                            Color = "#FF5722",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = false,
                            Name = "Utazás",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("ExpenseTrackerApi.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CategoryId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("Expenses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000001"),
                            Amount = 12500m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Heti bevásárlás",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000002"),
                            Amount = 8300m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Piaci vásárlás",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000003"),
                            Amount = 9500m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Havi bérlet",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000004"),
                            Amount = 4990m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Netflix előfizetés",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000005"),
                            Amount = 22000m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Villanyszámla",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000006"),
                            Amount = 6500m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gyógyszerek",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000007"),
                            Amount = 15000m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edzőterem bérlet",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000008"),
                            Amount = 3200m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tollak, füzetek",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000009"),
                            Amount = 14200m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Heti bevásárlás",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000010"),
                            Amount = 5600m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Étterem",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000011"),
                            Amount = 9500m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Havi bérlet",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000012"),
                            Amount = 4200m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Taxi",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000013"),
                            Amount = 18500m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gázszámla",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000014"),
                            Amount = 12000m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Koncertjegy",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0001-000000000015"),
                            Amount = 15000m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edzőterem bérlet",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0002-000000000001"),
                            Amount = 9800m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Heti bevásárlás",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0002-000000000002"),
                            Amount = 85000m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Repülőjegy",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0002-000000000003"),
                            Amount = 42000m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Szállás",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0002-000000000004"),
                            Amount = 15000m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fogorvos",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0002-000000000005"),
                            Amount = 19500m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Villanyszámla",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0002-000000000006"),
                            Amount = 11200m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Heti bevásárlás",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0002-000000000007"),
                            Amount = 8900m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mozi + vacsora",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0002-000000000008"),
                            Amount = 32000m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hétvégi kirándulás",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0002-000000000009"),
                            Amount = 4500m,
                            CategoryId = new Guid("cccccccc-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Könyvek",
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("ExpenseTrackerApi.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kiss.peter@example.com",
                            Name = "Nagy Tamás",
                            PasswordHash = "AQAAAAIAAYagAAAAEHashedPasswordPlaceholder1=="
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nagy.anna@example.com",
                            Name = "Kiss Anna",
                            PasswordHash = "AQAAAAIAAYagAAAAEHashedPasswordPlaceholder2=="
                        });
                });

            modelBuilder.Entity("ExpenseTrackerApi.Domain.Entities.Budget", b =>
                {
                    b.HasOne("ExpenseTrackerApi.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseTrackerApi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTrackerApi.Domain.Entities.Category", b =>
                {
                    b.HasOne("ExpenseTrackerApi.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ExpenseTrackerApi.Domain.Entities.Expense", b =>
                {
                    b.HasOne("ExpenseTrackerApi.Domain.Entities.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseTrackerApi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTrackerApi.Domain.Entities.Category", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
